title: Apps
description: A description of your site

# Remote theme settings
remote_theme: "mmistakes/minimal-mistakes"

# Enable dark mode
minimal_mistakes_skin: dark

# Emoji settings
emoji: true

# Plugins
plugins:
  - jemoji

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Site navigation (example)
header:
  nav:
    - text: "Home"
      url: "/"
    - text: "About"
      url: "/about/"
    - text: "Contact"
      url: "/contact/"

# Enable syntax highlighting (optional)
highlighter: rouge
